name: Clojure CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: clojure:temurin-24-lein-trixie-slim
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: lein test :unit
